export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';
export const UPDATE_USER_DATA = 'UPDATE_USER_DATA';
export const LOGIN = 'LOGIN';
export const UPDATE_INFOR = 'UPDATE_INFOR';

export const SHOWLOADING = 'SHOWLOADING';
export const HIDELOADING = 'HIDELOADING';

export const PUSHNOTI = 'PUSHNOTI';
export const HIDENOTI = 'HIDENOTI';

export const UPDATE_NOTIFICATION = 'UPDATE_NOTIFICATION';
export const UPDATE_NOTIFICATION_SUCCESSED = 'UPDATE_NOTIFICATION_SUCCESSED';
export const UPDATE_NOTIFICATION_FAIL = 'UPDATE_NOTIeFICATION_FAIL';

export const UPDATE_REPORT_SUCCESSED = 'UPDATE_REPORT_SUCCESSED';

export const UPDATE_REPORT = 'UPDATE_REPORT';
export const SAVENAVIGATE = 'SAVENAVIGATE';

export const NEW_SCREEN = 'NEW_SCREEN';
export const CLEAR_SCREEN = 'CLEAR_SCREEN';
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
