export const LOGINSCREEN = "LOGINSCREEN";
export const HOMESCREEN = "HOMESCREEN";
export const NOTIFICATION_SCREEN = "NOTIFICATION_SCREEN";
export const TABNAVIGATOR = "TABNAVIGATOR";
export const NEWSCREEN = "NEWSCREEN";
export const SCHEDULESCREEN = "SCHEDULESCREEN";
export const TESTSCHEDULE = "TESTSCHEDULE";
export const STUDYRESULT = "STUDYRESULT";
export const TUITION = "TUITION";
export const REVIEWS = "REVIEWS";
export const ACCOUNT = 'ACCOUNT';
export const RESULTKY1 = 'RESULTKY1';
export const RESULTKY2 = 'RESULTKY2';
export const SURVEYSTEP1 = 'SURVEYSTEP1';
export const SURVEYSCREEN = 'SURVEYSCREEN';
export const NOTIFICATION_DETAILS = 'NOTIFICATION_DETAILS';
export const TUITION_DETAILS = 'TUITION_DETAILS';
export const EVALUTE_TEACHING = 'EVALUTE_TEACHING';
export const EVALUTE_USER = 'EVALUTE_USER';
export const NOTE_SCREEN = 'NOTE_SCREEN';
export const STUDYRESULT_DETAIL = 'STUDYRESULT_DETAIL';
export const CONTACT = 'CONTACT';
export const ADMISSONS_WEBVIEW = 'ADMISSONS_WEBVIEW ';




